### ISSUE TITLE
Just some questions about downloading Bendy VR

### ISSUE THREAD

**Issue by Conster7790** [baggyg/BendyVR#17]
How do I get Bendy VR to show up on my oculus while its connected to my laptop. Where do I put the Bendy VR files in the Bendy And The Ink Machine files? Where do I teambeefinstaller.exe or what is that because it says I need it. Also what do I need Steam VR for?

**Comment by baggyg** [comment]
Do you have virtual reality already working on your laptop and have run other games? 
You need SteamVR because that is the API the mod uses (for input bindings etc). 

You want to connect your Oculus to the laptop via either AirLink or Link (plenty of tutorials online). 

Then follow the instructions on the readme. The Installer can be found on the latest release. Its a rar file you you need to unrar it to get the contents.
